version: "3.8"

services:
  fastapi:
    container_name: li-fast
    build:
      context: ./app/build/fastapi
      dockerfile: Dockerfile
    volumes:
      - ./app/public/fastapi/src:/code/src/
    networks:
      - app-network
    ports:
      - 4321:4321
  nginx:
    container_name: li-nginx
    build:
      context: ./app/build/nginx
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - 8080:80
    volumes:
      - ./app/public/html/:/var/www/html/
  php:
    container_name: li-php
    build:
      context: ./app/build/php
      dockerfile: Dockerfile
    networks:
      - app-network
    volumes:
      - ./app/public/html/:/var/www/html/
  mysql:
    container_name: li-sql
    build:
      context: ./app/build/mysql
      dockerfile: Dockerfile
    networks:
      - app-network
    # env_file:
    #   - ./app/env/mysql.env

networks:
  app-network:
    name: app-network
    driver: bridge
